name: Build & Deploy to University Server

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Unfreeze lockfile
      run: bundle config set frozen false

    - name: Install Ruby gems
      run: |
        gem install bundler
        bundle update  # this will regenerate Gemfile.lock dynamically

    - name: Run Python Scripts
      run: |
        python test.py
        python pubmerge.py

    - name: Build Jekyll Site
      run: bundle exec jekyll build --trace

    - name: Commit and push updated publications file
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add _data/OldPubs.json
        git add publications.json
        git commit -m "🤖 Auto-update: Merged new publications into OldPubs.json" || echo "No changes to commit"
        git push origin main
        
    - name: Copy site to university server via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: webserv3.rz.uni-jena.de
        username: atthdanishfurkh
        password: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "_site/*"
        target: "web/"

