name: Build Jekyll Site with Python and Protobuf

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GEM_HOME: ${{ github.workspace }}/.gem

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # -------------------------------
      # Python Setup
      # -------------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          pip install requests beautifulsoup4

      # -------------------------------
      # Ruby / Jekyll Setup
      # -------------------------------
      - name: Install Ruby and Bundler
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential ruby-dev
          export PATH="$GEM_HOME/bin:$PATH"
          gem install bundler jekyll

      # -------------------------------
      # Protobuf Compiler & Ruby Google Protobuf Gem
      # -------------------------------
      - name: Install Protobuf and Ruby Google Protobuf
        run: |
          sudo apt-get install -y protobuf-compiler
          export PATH="$GEM_HOME/bin:$PATH"
          gem install google-protobuf

      # -------------------------------
      # Bundle Install and Jekyll Build
      # -------------------------------
      - name: Install Ruby gems
        run: |
          export PATH="$GEM_HOME/bin:$PATH"
          bundle config set path "$GEM_HOME"
          bundle install
          bundle update

      - name: Build Jekyll site
        run: |
          export PATH="$GEM_HOME/bin:$PATH"
          bundle exec jekyll build

      - name: Upload Jekyll site artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site/
